<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DigitalTwinA4WZ2.Acquisition\DigitalTwinA4WZ2.Acquisition.csproj" />
    <ProjectReference Include="..\DigitalTwinA4WZ2.Domain\DigitalTwinA4WZ2.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
